title: Java Concepts
author: Jan Villapaz
email: janvillapaz@outlook.com
description: >-
  A simple blog to help me understand and explain core Java concepts.

baseurl: "/java-concepts" # ONLY needed for project pages
url: "https://janvillapaz.github.io"

remote_theme: pages-themes/modernist@v0.2.0

# Optional: social links
instagram_username: iamnotgian
github_username: JanVillapaz

# Build settings
plugins:
  - jekyll-remote-theme
